/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/portfolio/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all active holdings (with live P&L)
         * @description Return all currently held positions, annotated with live P&L from latest prices.
         */
        get: operations["list_holdings_portfolio_holdings_get"];
        put?: never;
        /**
         * Record a BUY (creates or adds to a holding)
         * @description Record a BUY transaction. Holding is recomputed and returned.
         *
         *     Symbol+exchange is resolved to ISIN via yfinance. If the holding already
         *     exists, this just adds another lot (FIFO).
         */
        post: operations["add_buy_portfolio_holdings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings/{isin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single holding by ISIN (with live P&L) */
        get: operations["get_holding_portfolio_holdings__isin__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit holding metadata (notes, thesis, alerts) — NOT quantity
         * @description Update editable metadata. Quantity & cost are derived; not editable here.
         */
        patch: operations["patch_holding_portfolio_holdings__isin__patch"];
        trace?: never;
    };
    "/portfolio/holdings/{isin}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get price history (OHLCV) for a holding
         * @description Return the last N trading days of OHLCV for this ISIN.
         *
         *     Args:
         *         isin: instrument ISIN
         *         days: number of trading days to return (default 90, max 2000)
         *
         *     Returns:
         *         List of {date, open, high, low, close, volume} sorted oldest → newest.
         *         Empty list if no price data available.
         */
        get: operations["get_holding_history_portfolio_holdings__isin__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings/{isin}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all transactions for a stock
         * @description Return all transactions (BUY/SELL/DIVIDEND/etc.) for one stock, oldest first.
         */
        get: operations["list_transactions_portfolio_holdings__isin__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings/{isin}/sell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a SELL (FIFO depletion)
         * @description Record a SELL. FIFO depletion happens during recompute. If quantity goes to 0,
         *     the holding is soft-deleted and 204 is returned.
         */
        post: operations["sell_portfolio_holdings__isin__sell_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{exchange}/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up an instrument by exchange and symbol
         * @description Returns full metadata for an instrument, or 404 if not found.
         */
        get: operations["get_instrument_instruments__exchange___symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/search/{symbol_prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search instruments by symbol prefix
         * @description Find instruments whose symbol starts with the given prefix.
         *
         *     Useful for confirming an ICICI symbol exists in the NSE master before
         *     creating an override.
         */
        get: operations["search_instruments_instruments_search__symbol_prefix__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all symbol overrides
         * @description List overrides. Optionally filter by broker.
         */
        get: operations["get_overrides_instruments_overrides_get"];
        put?: never;
        /**
         * Add or update a symbol override
         * @description Map a broker's internal symbol to its canonical NSE/BSE symbol.
         *
         *     Validates that the target symbol exists in the instruments collection.
         */
        post: operations["create_override_instruments_overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/overrides/{source_broker}/{source_symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a symbol override */
        delete: operations["remove_override_instruments_overrides__source_broker___source_symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full portfolio summary with totals, movers, and sector breakdown
         * @description Returns top-level totals, top movers (by pct + by value), day's gainers/losers,
         *     concentration (top 5 holdings by value), and sector breakdown.
         *
         *     All amounts in INR. Decimal values returned as strings to preserve precision.
         */
        get: operations["portfolio_summary_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconciliation/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the most recent snapshot */
        get: operations["get_latest_reconciliation_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconciliation/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get snapshot history (newest first) */
        get: operations["get_history_reconciliation_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconciliation/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a manual snapshot with ICICI numbers */
        post: operations["post_snapshot_reconciliation_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconciliation/auto-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger an automatic snapshot (cron use)
         * @description Endpoint for the daily cron to call. Captures our-side numbers only.
         */
        post: operations["post_auto_snapshot_reconciliation_auto_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost-basis/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all active cost-basis adjustments (audit trail) */
        get: operations["list_adjustments_cost_basis_adjustments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddBuyRequest
         * @description Record a buy. ISIN is auto-resolved via the `instruments` collection
         *     (NSE master), or you can supply it explicitly to override.
         */
        AddBuyRequest: {
            /**
             * Symbol
             * @description e.g., 'INFY'
             */
            symbol: string;
            /**
             * Exchange
             * @default NSE
             */
            exchange: string;
            /** Quantity */
            quantity: number | string;
            /**
             * Price
             * @description Per-share price in INR
             */
            price: number | string;
            /**
             * Trade Date
             * Format: date-time
             */
            trade_date: string;
            /**
             * Total Fees
             * @default 0
             */
            total_fees: number | string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Isin
             * @description Optional override. By default, ISIN is looked up from the instruments collection. Supply this only if the symbol isn't in the master or you want to override the lookup.
             */
            isin?: string | null;
        };
        /** CreateOverrideRequest */
        CreateOverrideRequest: {
            /**
             * Source Broker
             * @default ICICI
             * @enum {string}
             */
            source_broker: "ICICI" | "ZERODHA" | "OTHER";
            /**
             * Source Symbol
             * @description Symbol as the broker shows it (e.g., 'SHK')
             */
            source_symbol: string;
            /**
             * Target Exchange
             * @default NSE
             */
            target_exchange: string;
            /**
             * Target Symbol
             * @description Canonical NSE symbol (e.g., 'SUDARSCHEM')
             */
            target_symbol: string;
            /**
             * Notes
             * @description Optional context
             * @default
             */
            notes: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HoldingMetadataPatch
         * @description Editable fields on a holding (NOT quantity / cost — those are derived).
         */
        HoldingMetadataPatch: {
            /** User Notes */
            user_notes?: string | null;
            /** Thesis */
            thesis?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Stop Loss */
            stop_loss?: number | string | null;
            /** Target Price */
            target_price?: number | string | null;
            /** Alert On */
            alert_on?: string[] | null;
        };
        /** ManualSnapshotPayload */
        ManualSnapshotPayload: {
            /** Icici Invested */
            icici_invested: number;
            /** Icici Current Value */
            icici_current_value: number;
            /** Icici Day Gain */
            icici_day_gain?: number | null;
            /** Notes */
            notes?: string | null;
            /**
             * Set As Baseline
             * @default false
             */
            set_as_baseline: boolean;
        };
        /** SellRequest */
        SellRequest: {
            /** Quantity */
            quantity: number | string;
            /** Price */
            price: number | string;
            /**
             * Trade Date
             * Format: date-time
             */
            trade_date: string;
            /**
             * Total Fees
             * @default 0
             */
            total_fees: number | string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_holdings_portfolio_holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    add_buy_portfolio_holdings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddBuyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_holding_portfolio_holdings__isin__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_holding_portfolio_holdings__isin__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingMetadataPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_holding_history_portfolio_holdings__isin__history_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_portfolio_holdings__isin__transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sell_portfolio_holdings__isin__sell_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isin: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SellRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_instruments__exchange___symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exchange: string;
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_instruments_instruments_search__symbol_prefix__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                symbol_prefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overrides_instruments_overrides_get: {
        parameters: {
            query?: {
                source_broker?: ("ICICI" | "ZERODHA" | "OTHER") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_override_instruments_overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_override_instruments_overrides__source_broker___source_symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_broker: "ICICI" | "ZERODHA" | "OTHER";
                source_symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_summary_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_latest_reconciliation_latest_get: {
        parameters: {
            query?: {
                snapshot_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_reconciliation_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_snapshot_reconciliation_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualSnapshotPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_auto_snapshot_reconciliation_auto_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_adjustments_cost_basis_adjustments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
